Dj_less5/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

Dj_less5/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:id>/', basketapp.basket_add, name='add'),
    path('remove/<int:id>)/', basketapp.basket_remove, name='remove'),
]

Dj_less5/geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include



#urlpatterns = [
    #re_path(r'^$', mainapp.main),
   # re_path(r'^catalog/product/$', mainapp.product),
   # re_path(r'^contacts/$', mainapp.contacts),
  #  path('admin/', admin.site.urls),
#]

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dj_less5/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.product, name='index'),
   path('<int:id>/', mainapp.product, name='category'),
   path('details/<int:id>/', mainapp.product_detail, name='details'),
]

Dj_less5/mainapp/models.py
from django.db import models

# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return f"{self.name}"

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

Dj_less5/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse
import datetime
from .models import ProductCategory, Product
import json
from basketapp.models import Basket

def main(request: HttpRequest):

    content = {
        'page_title': 'главная',

    }
    return render(request, 'mainapp/index.html', content)

def product(request: HttpRequest, id=None):
    links_menu = ProductCategory.objects.all()
    if id is not None:
        products = Product.objects.filter(category__pk=id)
    else:
        products = Product.objects.all()
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    if id:
        if id == '0':
            products = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=id)
            products = Product.objects.filter(category__pk=pk).order_by('price')

    content = {
        'page_title': 'каталог',
        'links_menu': links_menu,
        'products': products,
        'basket': basket,
        'category': category,
    }
    return render(request, 'mainapp/product.html', content)

def product_detail(request:HttpRequest, id=None):
    if id is not None:
        #item = Product.objects.get(pk=id)
        item = get_object_or_404(Product, pk=id)
        products = Product.objects.exclude(pk=id).filter(category__pk=item.category_id)
        links_menu = ProductCategory.objects.all()

        content = {
            'title': f'Товар:{item.name}',
            'item': item,
            'products': products,
            'links_menu': links_menu,
        }

        return render(request, 'mainapp/details.html', content)

def contacts(request: HttpRequest):
    # locations = [
    #     {
    #         'city': 'Москва',
    #         'phone': '+78142332211',
    #         'email': 'ivai@yandex.ru',
    #         'address': 'Парк Останкино, офис 392',
    #     },
    #
    #     {
    #         'city': 'Нижний Новгород',
    #         'phone': '+78142332211',
    #         'email': 'ivai@yandex.ru',
    #         'address': 'Парк Горького',
    #     },
    #
    # ]
    #
    # with open('mainapp/json/locations.json', 'w', encoding='utf-8') as tmp_file:
    #     json.dump(locations, tmp_file)

    with open('mainapp/json/locations.json', 'r', encoding='utf-8') as tmp_file:
        locations = json.load(tmp_file)

    content = {
        'page_title': 'контакты',
        'locations': locations,
    }
    return render(request, 'mainapp/contacts.html', content)

def today():
    return datetime.date.today()

def products_index(request: HttpRequest, id=None):
    pass

Dj_less5/mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/layout.html' %}
{% load staticfiles %}

 {% block content %}
 {% include 'mainapp/widgets/list.html' %}

        <h2 class="rubric">Напишите нам</h2>
        
        Имя <input class="input" type="text"  placeholder="Анатолий"> <br>
        Email <input class="mail" type="text" placeholder="anatoliy@mail.ru"><br>
        Выберите тему<br>
        <select>
            <option value="Претензия">Претензия</option>
            <option value="Благодарность">Благодарность</option>
            <option value="Пожелания">Пожелания</option>
            <option value="Иное">Иное</option>           
        </select> <br> 
        Напишите что душа пожелает <br>
        <textarea class="textarea" ></textarea> <br>
        <button type="submit">Отправить</button>
        <button type="resert">Очистить</button>
    <div class="location">
        {% if locations %}
            {% for location in locations %}
            <div class="location1">
                <h2>Адрес</h2>
                <h2>{{ location.city }}</h2>
                <p>Наш номер</p>
                <a href="tel:+78142332211">{{ location.phone }}</a>
                <address>{{ location.address }}</address>
                <p>{{ location.email }}</p>
                <p>Нас легко найти</p> <br>
            </div>
            {% endfor %}
        {% else %}
            <h2>В разработке</h2>
        {% endif %}
    </div>
    <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A3b608ec8e11d8f35636ec634a2b70d1278dd88d06f86d7af99fbb4cea9c7c74f&amp;width=390&amp;height=304&amp;lang=ru_RU&amp;scroll=true"></script>
{% endblock %}

Dj_less5/mainapp/templates/mainapp/details.html
{% extends 'mainapp/layout.html' %}
{% load static %}


 {% block content %}
<h2>{% now 'd-m-y' %}</h2>
 {% include 'mainapp/widgets/list.html' %}
  <div class="menu">
   {% include 'mainapp/widgets/inc_categories_menu.html' %}
  </div>

    <h2 class="rubric">Товар каталога</h2>
    <hr>
<div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{{ MEDIA_URL }}{{ item.image }}">
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ item.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ item.price }} <span>руб</span></p>

                {% if request.user.is_authenticated %}
                <a href="{% url 'basket:add' id=item.id %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                {% endif %}

                <div class="description-text">
                    <p>{{ item.description }}</p>
                </div>
            </div>
        </div>
                <h2>Похожие продукты</h2>
                <a class="explore" href="{% url 'products:index' %}">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
            </div>
   {% for product in products %}
    <div class="bloc">
    <a class="bloc-list" href="pipkin1.html"><img class="decorimg" src="{{ MEDIA_URL }}{{ item.image }}" alt="Миска"></a>
       <h5 class="bloc">{{ product.name }}</h5>
       <h5 class="bloc">{{ product.description }}</h5>
    </div>
   {% endfor %}

{% endblock %}

Dj_less5/mainapp/templates/mainapp/index.html
{% extends 'mainapp/layout.html' %}
{% load static %}

 {% block content %}
 {% include 'mainapp/widgets/list.html' %}
  <div class="menu">
   {% include 'mainapp/widgets/inc_categories_menu.html' %}
  </div>
 <h2>Магазин керамической посуды Stonewear</h2>
<img src="{% static 'img/ceramic.jpg' %}" alt="Посуда"/>
<p>Представляем вашему вниманию наш прекрасный магазин, где каждый найдет себе что-то по&nbsp;душе!</p>
<p>С&nbsp;помощью керамических посудных наборов возможно выполнять любую красивую сервировку стола</p>
<p> Непоторимый дизайн и&nbsp;долгий срок службы будет радовать Вас каждый день.</p>
<hr>
<p>Кухонная керамическая посуда экологически безопасна, не&nbsp;вызывает аллергии, имеет привлекательный внешний вид<br>
и&nbsp;при бережном отношении может прослужить довольно долгое время. <br>
Разнообразный дизайн посуды из&nbsp;керамики поможет ей&nbsp;гармонично вписаться практически в&nbsp;любой интерьер кухни. <br>
К&nbsp;тому&nbsp;же керамическая посуда может использоваться не&nbsp;только для сервировки стола, но&nbsp;и&nbsp;для готовки.</p>
{% endblock %}

Dj_less5/mainapp/templates/mainapp/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ page_title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock %}

</head>
<body>
<div class="container">
    {% block menu %}
    {% endblock %}

    <div class="content">
    {% block content %}
    {% endblock %}
    </div>


    {% block footer %}
    <div class="footer">
        <footer class="foter">
           &copy;
        Все права защищены.
        </footer>
    </div>
    {% endblock %}
</div>
</body>
</html>

Dj_less5/mainapp/templates/mainapp/product.html
{% extends 'mainapp/layout.html' %}
{% load static %}


 {% block content %}
<h2>{% now 'd-m-y' %}</h2>
 {% include 'mainapp/widgets/list.html' %}
  <div class="menu">
   {% include 'mainapp/widgets/inc_categories_menu.html' %}
  </div>

    <h2 class="rubric">Товар каталога</h2>
    <hr>
   {% for product in products %}
    <div class="bloc">
    <a class="bloc-list" href="pipkin1.html"><img class="decorimg" src="/media/{{ product.image }}" alt="Миска"></a>
       <h5 class="bloc">{{ product.name }}</h5>
       <h5 class="bloc">{{ product.description }}</h5>
    </div>
   {% endfor %}
    
    <h2 class="rubric">Немного о нашем продукте</h2>
    <p class="write-up">В настоящее время керамическая посуда широко применяется многими ресторанами и кафе. Поданные в ней блюда выглядят очень аппетитно<br>
    и привлекательно. Кроме того, они сохраняют свой первоначальный вкус и аромат. <br>
    В нашем интернет магазине авторская керамическая посуда представлена в большом ассортименте изделий: <br>
    салатников, чашек, тарелок, вазочек, блюд. <br>
    Благодаря многообразию цветовой гаммы и форм эта столовая посуда идеально подойдет под любой стиль интерьера, начиная от классического<br>
    и заканчивая модным хай-теком или минимализмом. <br>
    Любая керамическая посуда изготавливается только из экологически чистых, пластичных материалов. <br>
    Это глина, кварц, полевой  шпат, каолин. Смесь природных материалов спекается при очень высоких температурах, что позволяет получить<br>
    прочное и надежное изделие из керамики.
    <br>
    Приемы обработки и украшения поверхности изделий в каждом конкретном случае будут разные, поэтому всю столовую керамическую посуду можно<br>
    разделить на несколько видов: майолика, фаянс, терракота, фарфор.</p>
    <h2 class="rubric">Особенности использования и ухода</h2>
    <p class="write-up">С керамической посудой стоит обращаться очень осторожно – ведь она весьма хрупкая.
    При использовании столовых предметов из керамики стоит учитывать, что этот материал нельзя подвергать резким температурным перепадам. <br> Керамическую посуду можно мыть вручную или в посудомоечной машине, но хрупкие предметы лучше вымыть руками. <br>
    Также при очищении и мытье не стоит использовать металлические мочалки, чтобы не допустить повреждения поверхности предметов. <br>
    После мытья керамику без глазури необходимо хорошо протирать полотенцем, чтобы исключить появление трещин. <br>
    При бережном отношении к столовой утвари из керамики она будет много лет радовать своим привлекательным внешним видом и практичностью.</p>
   
   
   
    <h2 class="rubric">Преимущества керамической посуды</h2>
    <ul class="plus">
        <li>термостойкость;</li>
        <li>абсолютную безопасность для здоровья, которая обеспечивается полной экологической чистотой материала;</li>
        <li>исключение пригорания пищи;</li>
        <li>можно использовать для микроволновой печи, духовки (электрической или газовой), плиты;</li>
        <li>идеальна для мультиварки;</li>
        <li>легко моется вручную или машиной, допускается использование моющих средств.</li>
    </ul>
    <p class="specification">Единственным недостатком посуды из керамики является способность материала впитывать растительные и животные жиры. <br>
    Не распространяется это свойство только на посуду, покрытую глазурью.</p>
{% endblock %}